first_user = User.create!(name: 'Alex', photo: 'https://drive.google.com/file/d/1Rf6vRehHE5NqXss9gvR8Xh2KCCKcZR3n/view?usp=sharing', bio: 'Full-Stack Web Developer')
second_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
third_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')

first_post = Post.create(user_id: first_user.id, title: 'Hello', text: 'Wanna grab a coffee?')
second_post = Post.create(user_id: User.first.id, title: 'Bye', text: 'See you later')
third_post = Post.create(user_id: User.first.id, title: 'Hello Rails', text: 'Learning Rails')
fourth_post = Post.create(user_id: User.first.id, title: 'RoR', text: 'Ruby on Rails')

Comment.create(post_id: first_post.id, user_id: second_user.id, text: 'Hi Alex!' )
Comment.create(post_id: first_post.id, user_id: third_user.id, text: 'Sure, I will join you all' )
Comment.create(post_id: first_post.id, user_id: third_user.id, text: 'Do you know Rails Coffee?' )
Comment.create(post_id: first_post.id, user_id: first_user.id, text: 'No, I have not been there yet!' )
Comment.create(post_id: first_post.id, user_id: third_user.id, text: 'It is an amazing place' )
Comment.create(post_id: first_post.id, user_id: third_user.id, text: 'And also is here, in the next block' )
